# METHODS {#sec:methods}

## STUDY AREA
The study area was designed to correspond with the area impacted by TMX Project-related marine shipping, including relevant sections of the marine shipping route between the Westridge Marine Terminal and Swiftsure Bank (i.e., the Strait of Georgia, Boundary Pass, Haro Strait, Juan de Fuca Strait, and out to the 12-nautical-mile territorial sea limit off southwestern Vancouver Island; National Energy Board, 2019).

The study area is comprised of the inbound and outbound shipping lanes (traffic separation scheme, TSS) with a 6 km buffer on either side (Figure \@ref(fig:plot-study-area)). The TSS spans Canadian and U.S. waters, and understanding cetacean density and habitat use in adjacent U.S. portions of the marine shipping route is critical for informing impacts of vessel traffic and potential mitigation measures in the TMX Project area. However, restrictions associated with the COVID-19 pandemic required survey transects to be clipped to cover Canadian waters only for the period between September 2020 and October 2022. The 6 km buffer was designed to provide good coverage of each of the sections of the marine shipping route, while also allowing for a survey that could be completed in 5-6 days for the Canadian portions of the study area.

## SURVEY DESIGN
Systematic, boat-based cetacean surveys were designed to be conducted monthly throughout the study area. For the purposes of survey design, the area was divided into seven sections and transect lines were generated for each section. This enabled the angles of the transect lines to vary among sections, which minimized off-effort transit time between transects and allowed the majority of transect lines to run perpendicular to depth gradients. A similar approach was used by Thomas et al. (2007) and Doniol-Valcroze et al. (in press). Effort was allocated equally across the seven sections, which were combined and analyzed as a single stratum.

The Distance Sampling Survey Design (dssd) R package (Marshall and Rexstad, 2021) was used to generate transect lines with an equal-spaced complementary zig-zag design. The survey design met the standard distance sampling assumption that all portions of the study area have an equal probability of being included in the sampled transect lines by using random start points generated in dssd for each iteration of the survey design. Several options for line spacing between 13 and 20 km were explored by conducting 1,000 simulations of potential survey designs to compare the mean estimated coverage based on a truncation distance of 2 km, and the mean total survey time for each design. A distance of 18 km between lines was selected to achieve a balance between minimizing the time required to conduct each monthly survey and maintaining good coverage throughout the study area. The survey design was used to generate different iterations of transect lines for each monthly survey.

## DATA COLLECTION

Surveys were conducted on a monthly basis when possible, given weather, vessel, and crew availability. The 12.8 m research vessel R/V Manyberries traveled along pre-determined transects at approximately 10 knots (18.5 km hr^-1^) when “on-effort” (i.e. actively surveying along transect lines). Data collected when vessel speed was less than 5 knots (9.2 km hr^-1^) or greater than 13 knots (24.1 km hr^-1^) were excluded from analyses. Observational effort was also halted when required for species confirmation or opportunistic photo-identification purposes. The order and direction that each line was surveyed varied between surveys, depending primarily on weather conditions throughout the study area.

One observer was positioned on each side of the vessel’s bow (285 cm average height of eye from sea level) and used 7x50 Fujinon binoculars to conduct observational effort from 0-90 degrees on each side of the transect line, plus a 10 degree overlap at the centre.  The data recorder was positioned inside the wheelhouse and recorded data from the observers using Mysticetus software (Steckler and Donlan, 2018). The observers and the data recorder rotated positions after every transect line, or after 45 minutes depending on transect length, to avoid eye strain and fatigue. Each observer worked independently to communicate sightings to the data collection station with in-ear Ultra High Frequency (UHF) radio headsets. All sightings included in the analyses were made by the same three observers.

Mysticetus, connected to GPS, automatically collected vessel position and speed every 10 seconds, and also recorded the positional coordinates and timestamp upon effort or sightings data entry.  Effort conditions were reported by observers at the start of each transect line and as conditions changed. These included visibility, Beaufort sea state, glare intensity, and swell height (Table \@ref(tab:cov)). Sightings data included the bearing and reticle reading (or visually estimated radial distance if the sighting was very close to the vessel) to the animal(s), species, and group size (i.e. the number of animals spotted in a single detection). The reticle measurements built into the binoculars were used to determine the  distance to each sighting by counting down from the horizon or nearest land mass to the location of the sighting. Digital or manual protractors were used to measure the radial angles to the sighting and the glare extent.  

## DATA PROCESSING

Data were examined for accuracy and consistency using a custom-made R script adapted from Wright et al. (2021). Incomplete sighting records were corrected if possible or excluded from the analyses.

Radial sighting distances were calculated based on the reticle readings, distance to the horizon, and the observational height of eye (Buckland et al., 2001). In some cases, reticles were measured from the nearest land mass at the time of observation, rather than from the horizon. In such cases, distance to the land mass was calculated using a custom R script and this was used in place of distance to the true horizon. The perpendicular distance of each sighting from the transect line was calculated from the radial sighting distance and the bearing to the sighting.

## DETECTION FUNCTIONS

Detection functions (DFs) were fit to perpendicular sighting distances of each species using the ds() function in the R “Distance” package (Miller, 2017). Because the survey platform, protocols, and the team of observers remained consistent throughout the study period, DFs were informed by data from all seasons. Species abundance was estimated separately for each season.

Models were fit beginning with key-only models (half-normal, hazard-rate, and uniform keys), considered with and without adjustment terms. Environmental data (visibility, Beaufort sea state, swell, and glare), individual observer, and group size were considered as candidate covariates in the DFs. Covariates were added to the key-only models in a stepwise forward selection process. Comparisons were made between the key-only and each of the covariate models based on Akaike information criterion (AIC) values and goodness of fit using Cramer-von Mises tests and visual inspection of quantile-quantile (Q-Q) plots.

To determine an appropriate right-truncation distance, the selected DF was examined for the perpendicular distance at which the probability of detection was approximately 0.15, as recommended in Buckland et al. (2001).

Some covariate levels were pooled to ensure sufficient numbers of sightings in each covariate category. Beaufort sea state was pooled into three categories: 0-1, 2, and 3+. Group sizes of three and above were pooled together. Swell categories were pooled into categories of present or absent, and glare was pooled into categories of none/mild or severe to +/- 90 degrees. Visibility categories were examined both as recorded and described above, as well as pooled into categories of good/excellent and moderate/poor. Visibility was only used in humpback whale models and was analyzed using the original categories. The selected categories were consistent among all species.

## SEASONAL ABUNDANCE ESTIMATES

Months were grouped into seasons as: winter (January to March), spring (April to June), summer (July to September), and fall (October to December). Abundance ($\hat{N}$) was estimated seasonally, using a Horvitz-Thomson-like estimator:


$$
\hat{N} = \frac{A}{2L} \sum_{i=1}^n f(0|{z_i})*{s_i}
$$

where `A` is the total study area (in the current report, only the Canadian portion of the full study area), `L` is the total length of transects surveyed for that season, `n` is the number of sightings for the species in that season, $f(0|z_i)$ is the probability density function of detected distances at zero perpendicular distance for observation `i` with covariates $z_i$, and $s_i$ are the group sizes.

Given abundance, density ($\hat{D}$) was estimated per season as: 

$$
\hat{D} = \hat{N}/A
$$

95% log-normal confidence intervals were calculated for abundance and density estimates following methods described in Buckland et al. (2001). 


