---
title: "03_results_outline"
author: "EK"
date: "2/23/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Results Section: 

Tables to be included: 

Number of sightings, individuals, and mean group size for each species (incl. min and max group size, and std dev of group size) 

“Survey Sightings” table – need to change to standard deviation, leave in min and max 

Model summaries for top 5ish(?) models for detection functions for the three species for which we have a sufficient number of sightings (humpback whales, harbour porpoise, Dall’s porpoise) – include measures of fit 

 

Abundance estimates for (Look at all four seasons, then decide what to include) for each of the three species, including CVs  

 

Figures to include: 

Map of survey area – include U.S waters (hatched or something) and place names 

 

Seasonal realized effort to date 

Split by winter (Jan – Mar), spring (Apr – Jun), summer (Jul – Sept), fall (Oct – Dec) 

Include total on-effort distance covered for each season (in km) 

 

“ 1.1.1 “CeMoRe survey completed transects” 

 

Plots showing levels of each covariate and sighting distances at each level (violin plots?)  

Include sample size of sightings for each covariate level  -After truncation

Covariates: Beaufort, swell, glare, visibility, observer, group size  

 

Can include just one example for each species in this first outline (i.e. one covariate per species) – HP and Beaufort; HW and observer 

 

Plots showing best detection function model for each of the three species, including histogram of sightings (similar to what is in PRISMM paper) 

 

Map of sightings of other species (FW, KW…) – all in one map 

 

 

Examples of how species distribution can vary seasonally/monthly 

Monthly sightings of our three key species 

 

 