# DISCUSSION {#sec:discussion}

As the first year-round, multi-species systematic cetacean survey effort to cover the Canadian portions of the southern Salish Sea and Swiftsure Bank, this study provides preliminary estimates of seasonal abundance and density for the three most frequently encountered species of cetacean in the TMX Project area. The results confirm that all three species are present in this area year-round.

## HUMPBACK WHALES

The survey results provide evidence of the year-round use of the study area by humpback whales. Generally, humpbacks that feed in the waters off southern B.C. between spring and fall are known to migrate to Hawaii, Mexico, or Central America for the winter (Calambokidis et al., 2008; Barlow et al., 2011). However, humpback whales were observed in the study area during all seasons. The presence of humpbacks in  the study area year-round is an important consideration for any measures to address the threats of vessel strikes and noise to this population.

Humpback whales were detected on Swiftsure Bank during all seasons, with high densities of sightings in this area in spring, summer, and fall (Figure \@ref(fig:monthly-hw)). The results of the systematic cetacean line-transect surveys conducted coast-wide in 2018 did not highlight Swiftsure Bank as an area of predicted high humpback whale density (Wright et al., 2021). However, earlier systematic aerial surveys predicted high humpback density in this area (Nichol et al., 2017), and Swiftsure Bank was previously identified as critical habitat for humpback whales (Fisheries and Oceans Canada, 2013), prior to their legal listing changing from Threatened to Special Concern in 2017. Nichol et al. (2017) also predicted high densities of humpback whales to the north and west of the study area boundaries, indicating that the impacts of vessel traffic on this population extend beyond the area surveyed.

The selected model for humpback whales was a uniform key function that included a cosine series adjustment. Half-normal and hazard-rate models including visibility as a covariate had almost identical support to the selected model based on AIC. Average detectability was slightly lower for the uniform model, leading to higher seasonal humpback whale abundance estimates than those generated by the models that included covariates. This sensitivity to the choice of different models with identical support creates additional uncertainty in the abundance estimates not represented in the confidence intervals. Increasing the sample size and using model-averaging can potentially resolve this uncertainty in future analyses.

The results of these surveys corroborate observations from previous systematic and opportunistic effort indicating the rapid increase in humpback whale use of the southern Salish Sea in recent years following decades of absence as a result of commercial whaling. During the systematic cetacean surveys conducted in 2004, no humpback whales were sighted in the southern Salish Sea (Williams and Thomas, 2007). Since that time, humpback whale numbers have increased significantly in the study area as the species reoccupied historical habitat (Merilees, 1985). In the current study, humpback whale abundance was estimated at 274 individuals, and density at over 2.3 whales per 25 km^2^ during fall for the entire study area.

During the coast-wide survey in summer 2018, Wright et al. (2021) predicted density of humpback whales within the Salish Sea to be highest in parts of Juan de Fuca Strait, with over three animals per 25 km^2^. Predicted density in the southern Strait of Georgia, however, where a large number of humpback whales were detected in October 2020 and 2021, was less than one animal per 25 km^2^ (Wright et al., 2021). In the future, spatially-explicit seasonal density estimates based on ongoing survey efforts can further inform seasonal trends in humpback whale habitat use.

## HARBOUR PORPOISE

Harbour porpoises were sighted year-round, with the highest number of detections in fall and the lowest in winter. However, the number of harbour porpoise sightings was high year-round, especially in Haro and eastern Juan de Fuca Straits. Hall (2004) estimated a significantly higher abundance of porpoises in Haro and eastern Juan de Fuca Straits from April – October, compared to November – March. Based on encounter rates, Hall (2004) identified August to October as months with the highest numbers of porpoise sightings. Similar patterns of high numbers of detections in September and October were observed during the 2020-22 surveys, but these surveys identified another, previously unreported period of increased harbour porpoise sightings in March, April, and May (Figure \@ref(fig:monthly-hp)).

This study identified Haro and eastern Juan de Fuca Straits as the areas with the highest numbers of harbour porpoise sightings. These corresponded with areas of predicted high harbour porpoise density from surface density models based on 2004 and 2018 cetacean surveys (Best et al., 2015; Wright et al., 2021). However, neither of these models highlighted the areas in the southern Strait of Georgia close to Vancouver where a large number of harbour porpoises were detected in some months, especially January, February, and April (Figure \@ref(fig:monthly-hp)). This difference may be explained by the multi-season nature of the current study; both former studies were conducted during summer only. Seasonal shifts in distribution and the potential for interannual variability in abundance and distribution are primary reasons why additional survey effort is required to better understand cetacean habitat use of the study area.

The harbour porpoise data showed a spike near zero perpendicular distance, which can be a sign of responsive movement toward the vessel. However, harbour porpoises are not known to approach vessels to bow-ride. Best et al. (2015) and Doniol-Valcroze et al. (in press) also found spikes close to zero perpendicular distance for harbour porpoises and concluded that the steep declines in detection probabilities likely accurately reflected observers’ abilities to detect harbour porpoises. If, however, responsive movement toward the vessel did occur, this could result in over-estimation of harbour porpoise abundance in the study area. 

The selected detection function for harbour porpoises included Beaufort and individual observer as covariates. Perpendicular sighting distance plots illustrate that at Beaufort 3 or higher, there were very few detections at larger distances (Figure \@ref(fig:violin-hp-bf)). Given the small size, low profile, and often cryptic behaviour of harbour porpoises, it is not surprising that sea state impacted detection distances for this species. The lack of sightings of harbour porpoises at high Beaufort levels makes it difficult to accurately model the impact of these higher sea states on detection probability. The unsheltered waters of the western-most portions of the study area (Swiftsure Bank and the mouth of Juan de Fuca Strait) tended to have higher sea states and swell heights during survey effort and this likely impacted the ability to detect harbour porpoises in these areas. Acoustic data collection is underway to address this challenge. Acoustic detections of harbour porpoise based on their vocalizations  will provide further insight into harbour porpoise use of the exposed portions of the study area.

## DALL'S PORPOISE

Dall’s porpoises were detected during all monthly surveys but at a lower estimated abundance than harbour porpoises in all seasons. Estimated abundance of Dall’s porpoises was highest in winter, when the estimated seasonal abundance for harbour porpoises was lowest (Figure\@ref(fig:plot-ab)). Analysis of stomach contents has indicated that harbour and Dall’s porpoises have significant overlap in prey species in the Salish Sea (Nichol et al., 2013), so their respective seasonal trends in abundance may indicate that there is some temporal partitioning of habitat between these two species.

As with harbour porpoises, the Dall’s porpoise data showed a moderate spike near zero perpendicular distance. Unlike harbour porpoises, however, Dall’s porpoises are known to show responsive movement toward vessels to bow-ride, and this behaviour was observed several times during survey efforts. Responsive movement toward the vessel could result in an over-estimate of Dall’s porpoise abundance. In the surveys reported on in Best et al. (2015), the behaviour of approximately 5% of the Dall’s porpoises detected was noted as “approaching”. Consequently, Best et al. (2015) and Williams and Thomas (2007) selected half-normal models with slightly higher AICs for their Dall’s porpoise detection functions, rather than hazard-rate models that tracked these spikes in the data, to correct for responsive movement in their detection function. In this study, the model with the lowest AIC was already a half-normal model that did not exhibit a sharp decline close to zero perpendicular distance.  Behaviours associated with responsive movement (e.g. approaching or bow-riding behaviour) will be recorded in future surveys, to inform the extent that responsive movement may be impacting detection functions.

## OTHER SPECIES

Systematic survey efforts to date have resulted in a total of 21 killer whale sightings, a sample size that is too small to reliably fit detection functions either by ecotype or grouped by species. However, With continued survey effort it is plausible that enough data could be collected (usually 60-80 sightings; Buckland et al., 2001) to provide seasonal and spatially explicit density estimates for killer whales. The populations of both southern resident and Bigg’s killer whales are monitored through photo-identification (Center for Whale Research, 2022; Towers et al., 2019) and there is extensive recent research focused on the occurrence and habitat use of southern resident killer whales in the study area (e.g. Ford et al., 2017; DFO, 2021). As Bigg’s killer whales, a Threatened population under SARA, have increased their use of the Strait of Georgia in recent decades (Ford et al., 2013), further insight into their seasonal habitat use could help to inform measures under TMX Recommendations 5 and 6, and contribute to refining the identification of habitats required for the survival and recovery of this population.

Fin whales were encountered twice in the study area, both times in Juan de Fuca Strait during summer 2021. Although no fin whales were detected in this area during systematic cetacean surveys conducted in 2004 or 2018 (Williams and Thomas, 2007; Doniol-Valcroze et al., in press), fin whales in the waters between Vancouver Island and the mainland have been documented several times since 2005 (Towers et al., 2018). The highest impact threats to fin whales (listed as Threatened under SARA) are collisions with and noise from ships (COSEWIC, 2019). Twelve dead fin whales, all with evidence of vessel strikes, were documented in the southern Salish Sea between 1986 and 2017 (Towers et al., 2018). Despite their relatively infrequent presence in the area, fin whales are highly susceptible to vessel strikes and should be considered in measures to address vessel impacts from Project-related shipping.  

Grey and minke whales were not detected while surveying along pre-determined transect lines, but were sighted three and two times, respectively, during periods of off-effort transiting. Eastern North Pacific grey whales are currently listed as special concern under SARA, and the Committee on the Status of Endangered Wildlife in Canada (COSEWIC) has recommended splitting grey whales into three populations, including two assessed as Endangered (COSEWIC, 2017). Vessel strikes are considered one of two principal threats to the survival and recovery of grey whales (Gavrilchuk and Doniol-Valcroze, 2021) and vessel traffic in the study area has the potential to impact members of these populations. Minke whales are known to feed in parts of the study area, including southern Haro and eastern Juan de Fuca Straits (Towers et al., 2013). Their erratic surfacing patterns and lack of a visible blow make them difficult to detect visually, especially when weather conditions are not ideal. Accurate assessments of abundance and habitat use are therefore challenging for this species. 

## ASSUMPTIONS AND UNCERTAINTY

All distribution and abundance information from this technical report should be interpreted with caution, as more data are required to sufficiently capture seasonal and interannual variability. Additionally, the distributions of each species described in this report are based on detections alone; factors including environmental conditions and diel differences in habitat use have not yet been accounted for.

Caution is also needed when interpreting results for months and for areas that have had less coverage. At least one survey was conducted from the R/V Manyberries in every month except December, because required vessel repairs in December 2020 and 2021 precluded its use as a survey platform. Transect lines in the western-most portion of the study area (Swiftsure Bank, Figure \@ref(fig:plot-seasonal-track)) as well as the northern-most transect lines (near Vancouver) have been completed during a limited number of surveys thus far due to weather conditions. Additional surveys will provide for more consistent effort throughout the study area, resulting in more precise abundance and density estimates and informing seasonal and interannual variability.

To date, survey effort has been conducted in Canadian portions of the study area only. The survey design includes the U.S. portions of the southern Salish Sea and Swiftsure Bank, and with travel restrictions associated with the COVID-19 pandemic lifting, there are plans to include U.S. waters in future surveys. Understanding cetacean density and habitat use in adjacent U.S. waters is critical for informing impacts of vessel traffic and potential mitigation measures in the TMX Project area.

Visual surveys are limited to daylight hours only and thus do not capture diel changes in humpback whale and porpoise behaviour. These changes can affect detection patterns and could lead to some habitats being undervalued if based on daytime data alone (Calambokidis et al., 2019; Williamson et al., 2017). Additionally, harbour porpoises are very difficult to detect visually in sea states greater than Beaufort 2, likely impacting the number of detections in the more exposed portions of the study area.

Key assumptions for distance sampling include that animals are sighted at their initial locations (i.e. no directed movement prior to detection), that all animals are available at the surface to be counted, and that all available animals on the transect line are detected. Violation of the latter two assumptions can lead to availability bias or perception bias, respectively. The relatively low height of eye on the R/V Manyberries restricts the time and distance over which animals can be detected, which may impact when animals are sighted and the number of sightings on the trackline that are missed. For example, it is possible that the low height of eye of the platform influenced whether porpoises were detected prior to any directed movement.


The space available for observation on R/V Manyberries does not allow for a double-platform set-up to test if all animals on the trackline are detected and to estimate a perception bias correction. However, data collection are underway to correct for availability bias (the bias resulting from animals that are not detected due to being underwater). Time-depth recording tags deployed on humpback whales in the study area will provide data to inform correction factors for the abundance estimates. 

Violation of these assumptions could result in biased abundance and density estimates for cetaceans in the study area, as well as underestimation of the uncertainty associated with these estimates. However, the consistency in protocols and observers throughout these surveys means that these biases are unlikely to vary significantly in space or time, so they should not affect comparisons of relative density across seasons and areas.

## CONCLUSIONS AND NEXT STEPS

The preliminary results from data collected to date provide new insight into the seasonal presence and abundance of humpback whales, harbour porpoises, and Dall’s porpoises in the southern Salish Sea and Swiftsure Bank. These three species are present in the area year-round but there are strong seasonal differences in their abundance and distribution. 

Additional survey effort is needed to better understand seasonal and annual variability and to refine seasonal estimates of abundance. Best et al. (2015) found that incorporation of additional years of cetacean survey data following the 2004-05 surveys from Williams and Thomas (2007) altered abundance estimates and tightened confidence intervals for all cetacean species. It is therefore critical to continue survey efforts for several years for accurate abundance estimation. Additional years of survey effort will also provide sufficient data to use a density surface modeling approach for production of spatially-explicit predicted seasonal distribution maps.

Additional data collection is underway to address some of the limitations associated with diel behaviour patterns and weather. Time-depth recording tags are being deployed on humpback whales in the study area to investigate diel differences in fine-scale habitat use and dive behaviour, and how this may impact their vulnerability to vessel strikes. Because harbour porpoise detections are strongly affected by Beaufort sea state, deployments of autonomous acoustic recorders are underway to detect porpoise presence from their characteristic high frequency vocalizations. Future analysis of the acoustic data will show whether porpoise abundance has been underestimated by visual surveys in the more exposed parts of the study area and will provide a more complete picture of harbour porpoise distribution and habitat use.

# ACKNOWLEDGEMENTS {#sec:acknowledgements}

We would like to thank Stacey Hrushowy, Captain of the R/V Manyberries, for their skilled operation and maintenance of the vessel and their dedication to this program. We are grateful to Eva Stredulinsky, Brianna Wright, and Robin Abernethy for developing and sharing R code for data processing and providing advice on adapting code for our requirements. James Pilkington, Jackie Hildering, Wendy Szaniszlo, and the crew of the CCGS Vector assisted with survey efforts. We are grateful to the Non-Destructive Survey Tools Program and the Marine Invertebrates Program, especially Benjamin Snow, Seaton Taylor, and Janet Lochead, for making this work possible through sharing the use, maintenance, and expenses of the R/V Manyberries. Linda Nichol and Brianna Wright provided helpful comments on drafts of this report. We thank Sean MacConnachie for his support in securing resources for this project.
